### ISSUE TITLE
Add support for Temporal.cloud pinning service

### ISSUE THREAD

**Issue by agentofuser** [ipfs-shipyard/ipfs-deploy#21]
They support both IPFS and IPNS (cc #20) pinning.

**Comment by postables** [comment]
I don't personally feel comfortable with my JS skills to contribute quality code but I'll provide some guidelines:

Two methods of registering:

1) [api](https://gateway.temporal.cloud/ipns/docs.api.temporal.cloud/account.html#post-register)
2) [website](https://temporal.cloud)

Authentication is done via a JWT you receive via [login](https://gateway.temporal.cloud/ipns/docs.api.temporal.cloud/account.html#post-login) API call. Usual method of JWT authentication is used (aka passing the token in via a `Authorization` header).

To pin your hash directly you can use [this](https://gateway.temporal.cloud/ipns/docs.api.temporal.cloud/ipfs.html#post-pin-hash) API call. If you're just using a free account (ie, non-paid) leave the `hold_time` at 1 month, otherwise you can go all the way up to 2 years. To pin your IPNS record directly (ie, `/ipns/foo.bar`) you can use [this](https://gateway.temporal.cloud/ipns/docs.api.temporal.cloud/ipns.html#post-pin-ipns) API call.

If you'd rather not write the http requests and stuff, you can use [temporal-js](https://github.com/clemlak/temporal-js) to handle the login to retrieve the `jwt`, and also to handle pinning of IPFS hashes, but not IPNS.

**Comment by hacdias** [comment]
Closing in favor of #107
