### ISSUE TITLE
Update required version of node to 12

### ISSUE THREAD

**Issue by jasikpark** [ipfs-shipyard/ipfs-deploy#26]
Right now ipfs-deploy only builds on `node 10.15.3` whereas the stable version of `node` is `12.1.0`

I'd appreciate it if I didn't also need `nvm` to install this and could just use stable node

**Comment by agentofuser** [comment]
I managed to install with node 11, but tiny-secp256k1 compilation breaks under node 12. Will investigate further.

**Comment by agentofuser** [comment]
Waiting on `js-ipfs` to update dependency on tiny-secp256k1: https://github.com/ipfs/js-ipfs/issues/1941

**Comment by agentofuser** [comment]
@jasikpark you should be able to install it with npm and node 12 now. Yarn still won't work because of an outdated lockfile (npm doesn't consider lockfiles). Thanks to @alanshaw for the tip:

https://github.com/ipfs/js-ipfs/issues/1941#issuecomment-493437657

I'll keep the issue open until yarn works as well. Thank you for reporting it!

**Comment by jasikpark** [comment]
thanks!

**Comment by agentofuser** [comment]
Another step towards supporting node 12 + yarn: https://github.com/bitcoinjs/bitcoinjs-lib/pull/1398

Now gotta wait for bitcoinjs-lib to release a new version with the patch, and ipld-bitcoin to pick it up.

**Comment by hacdias** [comment]
Closing this since I'm using it successfully with node 12.
